FROM debian:7
RUN apt-get update

COPY Gemfile .

# Install Ansible
RUN apt-get install -y software-properties-common git ruby-dev ruby build-essential curl python-pip python-dev libffi-dev
RUN pip install PyYAML jinja2 paramiko
RUN git clone https://github.com/ansible/ansible.git
RUN cd ansible && make install && mkdir /etc/ansible
RUN curl -L https://www.getchef.com/chef/install.sh | bash -s -- -P chefdk -v 0.9.0
RUN chef exec bundle install

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

VOLUME [ “/sys/fs/cgroup” ]
CMD [“/usr/sbin/init”]
