FROM debian:8
RUN apt-get update

COPY Gemfile .

# Install Ansible
RUN apt-get install -y software-properties-common git libwww-perl libdbi-perl libdbd-mysql-perl libgd-gd2-perl ansible ruby-dev ruby build-essential curl systemd perl wget
RUN curl -kL https://www.getchef.com/chef/install.sh | bash -s -- -P chefdk -v 0.9.0
RUN chef exec bundle install

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
